### ISSUE TITLE
Issue with trailing spaces in HTML

### ISSUE THREAD

**Issue by onkar0777** [ngx-rocket/starter-kit#11]
I have started using this project starter kit directly without using the ngx-translate separately or any other services. So I am not sure if this is an issue with any of the underlying libraries or some issue in this project. But in any case I hope you can guide me better.

Bug - `<span translate>
                   over60Message
             </span>`

The above code does not translate on changing the language from the top nav bar on home screen of this project. But it works on refreshing it.

This works in every case - `<span translate>over60Message</span>`

This can also be seen on the project login screen without any changes, on changing the language from the dropdown on login screen. The error messages do not get translated, but are correctly translated on a reload.

The code is similar with trailing spaces - `<small [hidden]="loginForm.controls.password.valid || loginForm.controls.password.untouched"
                       class="text-danger" translate>
                  Password is required
                </small>`

Where as the login button gets translated as soon as we select the new language, as it does not have any trailing spaces - `<span translate>Login</span>`

**Comment by sinedied** [comment]
This is definitely strange as ngx-translate should trim keys before translation, so space before/after should not matter. I think you should post your issue to the ngx-translate repo so they can fix the issue
