### ISSUE TITLE
Unable to create New Routes

### ISSUE THREAD

**Issue by navneet936** [ngx-rocket/starter-kit#13]
Hello

I am following all the steps for creating new routes, but still not being able to navigate to them.
When passed the new route path, it redirects to home page.

Thanks

**Comment by sinedied** [comment]
Please see https://github.com/ngx-rocket/starter-kit/issues/7

For your route problem, make sure your new routes gets imported *before* `AppRoutingModule` in `app.module.ts`, as `AppRoutingModule` include a fallback route that redirects to home.

**Comment by navneet936** [comment]
Thanks 
Issue Resolved
