### ISSUE TITLE
If you use i18Service to set LOCALE_ID language is undefined

### ISSUE THREAD

**Issue by whisher** [ngx-rocket/starter-kit#16]
Hi there,
sorry to bother you, this is not a real bug of ngx-rocket
but it could be an issue if you use  i18Service to set LOCALE_ID 
to localize i.e date pipe
AppModule
```javascript
providers: [
    {
      provide: LOCALE_ID,
      useFactory: (i18n: I18nService) => {
        console.log('locale ID', i18n.language);
        return i18n.language;
      },
      deps: [I18nService]
    }
  ],
```

If you use init method of i18n service in app.component
i18n.language is undefined
```javascript
this.i18nService.init(environment.defaultLanguage, environment.supportedLanguages);
```
to work it out you should put it inside the service.

Btw, do you a  know a way to localize pipe
without refresh the page?

All in all, when I see the text translate I'd like to see
the date in the right format and should be nice have this
feature in the starter-kit.

I found the way :) https://github.com/ngx-translate/core/issues/409#issuecomment-315240962
but it works only if you use init directly in the service.
Thanks for sharing :)

**Comment by sinedied** [comment]
`LOCALE_ID` can only be defined at app startup, so it won't work for this use case. Your best bet would be to create a custom pipe that forwards the `i18nService.language` value by default to the existing `datePipe`, as the locale can be passed on dynamically: https://angular.io/api/common/DatePipe

**Comment by whisher** [comment]
> LOCALE_ID can only be defined at app startup


Ok I know that  but put the case the user has just been in site and change
the lang to fr-FR the lang is saved in localStorage than the user close/open
the browser and without setting the LOCALE_ID providers the pipe displays
the US format.
If you set the LOCAL_ID using the in18Service the pipe displays the FR format.
I've put in the code a simple not very clean fallback

```javascript
get language(): string {
    const lang = this.translateService.currentLang;
    if (!lang) {
      return this.fallbackLang;
    }
    return lang;
  }
```

**Comment by sinedied** [comment]
If you do not care for supporting dynamic locale changes, then all you need to do to make it work properly is to call `i18nService.init()` before app startup and Angular initialize providers likes `LOCALE_ID`: you can use the special `APP_INITIALIZER` provider with your own factory to do just that, see https://hackernoon.com/hook-into-angular-initialization-process-add41a6b7e 😉 
Hope that helps.

**Comment by ganqqwerty** [comment]
@sinedied  What if I do care?

**Comment by sinedied** [comment]
`LOCALE_ID` cannot change at runtime, so if you need dynamic locale changes you have to roll out your own version of builtin pipes to support this, for example like this:
```ts
@Pipe({name: 'dynamicDate', pure: true})
export class DynamicDatePipe implements PipeTransform {
  constructor(private datePipe: DatePipe, private i18n: I18nService) {}

  transform(value: any): string|null {
    return this.datePipe.transform(value, undefined, undefined, this.i18n.language);
  }
}
```
