### ISSUE TITLE
Angular Universal

### ISSUE THREAD

**Issue by gregor-srdic** [ngx-rocket/starter-kit#19]
Great starter for Angular!
Could you please consider adding config and scripts for server-side rendering and pre-rendering using Angular Universal? Something like https://github.com/angular/universal-starter.

**Comment by bhushankummar** [comment]
Can we reopen this?

**Comment by sinedied** [comment]
Please read this: https://github.com/ngx-rocket/starter-kit/issues/7

Related issue on generator is https://github.com/ngx-rocket/generator-ngx-rocket/issues/230
