### ISSUE TITLE
Invalid module name in argument (After Upgrade Angular 8)

### ISSUE THREAD

**Issue by nagasundaram4** [ngx-rocket/starter-kit#21]
Hi,
I try to upgrade my app angular 7 to angular 8. but after the upgrade , I cannot build app anymore. I got below error. Please advice me. advance thanks
ERROR in src/app/core/http/http.service.ts(10,16): error TS2664: Invalid module name in augmentation, module '@angular/common/http/src/client' cannot be found.

**Comment by sinedied** [comment]
In `core/http/http.service.ts`, replace:
```
declare module '@angular/common/http/src/client' {
```
with
```
declare module '@angular/common/http/http' {
```

The Angular 8 update is currently WIP, but this should fix your issue.

**Comment by nagasundaram4** [comment]
its working fine now.Thanks for your quick response.
