### ISSUE TITLE
how to disable Auth 

### ISSUE THREAD

**Issue by mohd7469** [ngx-rocket/starter-kit#25]
how to disabled auth flow and start home page directly when page loads ?

**Comment by sinedied** [comment]
Use https://github.com/ngx-rocket/generator-ngx-rocket and select "no" when asked if you want authentication 🙂

**Comment by sinedied** [comment]
If already have a project started, you can simply remove the `AuthenticationGuard` in `ShellService` here: https://github.com/ngx-rocket/starter-kit/blob/master/src/app/shell/shell.service.ts#L21
