### ISSUE TITLE
using git not download

### ISSUE THREAD

**Issue by jagdishmastek** [ngx-rocket/starter-kit#3]
Hi,
I am trying to download the repo but it is't not downloading using git bash give below error.Please help.
$ https://github.com/ngx-rocket/starter-kit.git
bash: https://github.com/ngx-rocket/starter-kit.git: No such file or directory

Jagdish

**Comment by sinedied** [comment]
Try [using git](https://git-scm.com/docs/git-clone) maybe?
```sh
git clone  https://github.com/ngx-rocket/starter-kit.git
```
