### ISSUE TITLE
Impossible to run tests.

### ISSUE THREAD

**Issue by sammy44nts** [ngx-rocket/starter-kit#5]
Hello,
I've generated a project with [generator-ngx-rocket](https://github.com/ngx-rocket/generator-ngx-rocket) then I tried to run the tests and got the following error:
```
ERROR in /angular_v4_frontend/node_modules/@types/node/index.d.ts (102,13): Subsequent variable declarations must have the same type. 
Variable 'module' must be of type '{ id: string; }', but here has type 'NodeModule'.
```
It is fixed by changing the module declaration in starter-kit/src/typings.d.ts:
``` typescript
// SystemJS module definition
declare var module: {
  id: string;
};
```
by
``` typescript
// SystemJS module definition
declare var module: NodeModule;
```

**Comment by sinedied** [comment]
Already fixed by https://github.com/ngx-rocket/generator-ngx-rocket/pull/87

Since this repo is auto-generated from [generator-ngx-rocket](https://github.com/ngx-rocket/generator-ngx-rocket), it will be resolved once I publish a new generator version (should be later today)

**Comment by sammy44nts** [comment]
Ok, thanks :+1:
