### ISSUE TITLE
Not able to add new module

### ISSUE THREAD

**Issue by DonthuVenu** [ngx-rocket/starter-kit#8]
Hi Team,

i'm unable to add new module for this code. This only displaying "About" and "Home".

Could you please let me know the steps to add new module to this project?

Thanks,
Venu Donthu

**Comment by sinedied** [comment]
Please see https://github.com/ngx-rocket/starter-kit/issues/7

To add new navigations items, you have to edit the header component located in `app/core/shell/header`.
